### ISSUE TITLE
add additional `aerosol_t` extending class

### ISSUE THREAD

**Issue by mattldawson** [NCAR/demo-radiation#4]

**Comment by mattldawson** [comment]
Hi @gold2718

I tried to draft a second aerosol scheme for the toy model. When trying to build the model I get the following error:
```
 Running: /Users/mattdawson/git_repos/demo-radiation/ccpp_framework/scripts/ccpp_capgen.py --host-files
 /Users/mattdawson/git_repos/demo-radiation/src/model.meta --scheme-files
 /Users/mattdawson/git_repos/demo-radiation/src/musica_schemes.txt --suites
 /Users/mattdawson/git_repos/demo-radiation/src/toy_suite.xml --output-root /Users/mattdawson/git_repos/demo-radiation/build/ccpp
 --host-name demo_rad
 Subroutine, None, not found, at /Users/mattdawson/git_repos/demo-radiation/src/musica_aerosol_factory.F90:14

 CMake Error at CMakeLists.txt:55 (MESSAGE):
   CCPP cap generation FAILED: result = 1
```

I tried to follow the patterns for the meta data for radiation, but I am not very familiar with the structure of the meta data files. Would you be able to take a look? Hopefully you will be able to see where I was going with the code. It's on branch `develop-4-new-aerosol`

(I added you to the repo - sorry, I thought I had done this earlier)

**Comment by gold2718** [comment]
I think you need to add musica_aerosol_factory.meta to musica_schemes.txt (note that this file is one of the inputs to ccpp_capgen which can take a list of metadata files, a text file listing metadata files, or some combination).
Also, I do not see musica_aerosol_sectional.meta so that needs to be created and added to the musica_schemes.txt file.

**Comment by mattldawson** [comment]
ok, maybe getting closer. After looking at your PR #5 I made the following changes:
- updated ccpp submodule
- added dependencies to `musica_aerosol_factory` meta data:
https://github.com/NCAR/demo-radiation/blob/db49d67e9fe86f669206f73e658c6e2d10d39ec5/src/musica_aerosol_factory.meta#L1-L4
- changed the factory `_init` function to a subroutine and updated the meta data

But, now when I try to build the model, `ccpp_capgen.py` just hangs indefinitely at this point:
```
 Running: /Users/mattdawson/git_repos/demo-radiation/ccpp_framework/scripts/ccpp_capgen.py --host-files
 /Users/mattdawson/git_repos/demo-radiation/src/model.meta --scheme-files /Users/mattdawson/git_repos/demo-radiation/src/musica_schemes.txt
 --suites /Users/mattdawson/git_repos/demo-radiation/src/toy_suite.xml --output-root /Users/mattdawson/git_repos/demo-radiation/build/ccpp
 --host-name demo_rad
```

The only major difference I see between our two branches is that I'm passing the aerosol model as a pointer and yours is an allocatable variable. Could this be causing the error?

**Comment by gold2718** [comment]
Sorry for not noticing that the init scheme was a function. functions are not supported as CCPP interfaces.

I am able to reproduce the hang even without using aerosol as a pointer (also not generally supported by the CCPP due to performance issues).

I will look into this and get back to you (hanging is not best practice :)

**Comment by gold2718** [comment]
I found and fixed the issues (bad units that were not caught which then triggered a hand writing out the database).
For the record, `n/a` is not a valid unit (see [UDUNITS](https://www.unidata.ucar.edu/software/udunits/) for standard units usage).
You should be able to update the ccpp_framework submodule to move forward.
